### ISSUE TITLE
Configuration automation with Node.js

### ISSUE THREAD

**Issue by streamich** [adaltas/node-mecano#5]
There seem to be no alternative written in Node.js to Puppet or Chef, maybe this library can be used as a starting point?

**Comment by wdavidw** [comment]
u're right, this is a good starting point. you can see it in action inside [ryba](https://github.com/ryba-io/ryba). however, be warned, this is moving fast as i have a lot of changes for ryba and mecano. however, mecano shouldn't suffer much from backward compatibility. [masson](https://github.com/wdavidw/node-masson) leverage mecano is the closest thing from Puppet or Chef but it will suffer too many changes that i cant recommand it to you. by the way, i'm probably going to rename mecano soon.
